package main

import (
	"log"
	"os"
	"strings"
	"text/template"
)

// EclassData matches the output from our Regex-Rename sniffer
type EclassData struct {
	Eclass         string
	URLTemplate    string
	RenameTemplate string
}

func main() {
	if len(os.Args) < 4 {
		log.Fatal("Usage: gen-helpers <eclass> <url_template> <rename_template>")
	}

	data := EclassData{
		Eclass:         os.Args[1],
		URLTemplate:    os.Args[2],
		RenameTemplate: os.Args[3],
	}

	// Use a string template for portability, or keep your external .tmpl
	const helperTmpl = `// Code generated by Ghost-Hash-Bot; DO NOT EDIT.
package main

import "strings"

func init() {
	// Registering {{.Eclass}} into the Int.go registry
	EclassRegistry["{{.Eclass}}"] = func(pv, pn string) (string, string) {
		url := "{{.URLTemplate}}"
		rename := "{{.RenameTemplate}}"

		r := strings.NewReplacer(
			"${PV}", pv,
			"${PN}", pn,
			"${P}",  pn+"-"+pv,
		)

		return r.Replace(url), r.Replace(rename)
	}
}
`

	t, err := template.New("helper").Parse(helperTmpl)
	if err != nil {
		log.Fatalf("Template parse error: %v", err)
	}

	// Create a specific file for this eclass
	fileName := "helpers_" + strings.ReplaceAll(data.Eclass, "-", "_") + ".go"
	f, err := os.Create(fileName)
	if err != nil {
		log.Fatalf("Failed to create file: %v", err)
	}
	defer f.Close()

	err = t.Execute(f, data)
	if err != nil {
		log.Fatalf("Template execution error: %v", err)
	}

	log.Printf("👻 Generated %s for eclass %s\n", fileName, data.Eclass)
}
